version: "1.0"

services:
  script-service:
    build: ./script
    volumes:
      - db-data:/data
    depends_on:
      - db

  db:
    image: mcp/sqlite:latest
    volumes:
      - db-data:/data
    stdin_open: true
    tty: true

volumes:
  db-data:
